pub mod code_hygiene;
pub mod debug_remnants;
pub mod error_dropped_by_pattern;
pub mod fallible_new;
pub mod file_length;
pub mod handwritten_fmt;
mod hir_refs;
pub mod no_comments;
pub mod panic_in_drop;
pub mod proper_error_type;
pub mod pub_unused_in_workspace;
pub mod result_result;
pub mod result_defaulted;
pub mod serde_default_fn;
pub mod spawn_handle;
pub mod suppression;
pub mod test_hygiene;
pub mod topological_ordering;
mod topological_reorder;
pub mod typographic;
pub mod unclear_exports;
pub mod value_cloned_to_deserialize;
